apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gifthaven-chart.fullname" . }}-ai-ingress
  labels:
  {{- include "gifthaven-chart.labels" . | nindent 4 }}
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          service:
            name: '{{ include "gifthaven-chart.fullname" . }}-ai-service'
            port:
              number: 5173
        path: /
        pathType: Prefix
