apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: gifthaven-image-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "gifthaven-app"
      writeBackConfig:
        method: "git"
      images:
        - alias: "gifthaven"
          imageName: "parthsingh2496/gifthaven"